### ISSUE TITLE
Solution to C 3.53

### ISSUE THREAD

**Issue by ejortegau** [wdlcameron/Solutions-to-Data-Structures-and-Algorithms-in-Python#1]
Hi:
I do not think the solution given is correct, since it means that the evil king needs to wait a month between having each two testers have a go at the remaining halves. The problem requests that the bottle is found in just one month, which would mean that all testers need to drink whatever combination of bottles on day one. Unfortunately, I have not been able to come up with a better answer.

**Comment by wdlcameron** [comment]
Hello,

You are correct - thank you for pointing that out!  I misread the question and have updated the answer accordingly.  Here is the new answer:

- We can represent any number using log(n) digits in binary.
- Therefore, assign each wine bottle a binary value (ex. bottle 5 is 0000...0000101).
- Enlist one cup for each binary digit. and add a drop of that wine to the cup if there is a 1 in the binary representation.
- Ex. Wine 5 will be added to the first and third cup.
- After a month, the poison tasters killed will map out the binary representation of the poisoned wine.
- Ex. If wine 5 is poisoned then tasters 1 and 3 (starting from 1) will die but everyone else will live
- If wine 10 is poisoned (000...001010), wine tasters 2 and 4 will die but everyone else will live.

Note: this assumes that the poison tasters are physically capable of drinking one drop from half of the wines in a day which may not be feasible at huge numbers.
